version: '2.0'
services:
  pgc:
    build: ../.
    ports:
      - 5555:5555
    depends_on:
      - neo4j
    env_file:
      - ../config/.env
    networks:
      - neo4j_go_net
    restart: on-failure
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
    restart: on-failure
    networks:
      - neo4j_go_net
    command: neo4j
  pgl:
    build: ../pgl
    ports:
      - 6113:6113
    env_file:
      - ../PGL/config/.env
    volumes:
      - $HOME/pgl/logs:/logs
    networks:
      neo4j_go_net:
        ipv4_address: 172.19.0.3

    restart: on-failure

networks:
  neo4j_go_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16
        gateway: 172.10.0.1